{% set name = "xrootd" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xrootd/xrootd/archive/v{{ version }}-rc2.tar.gz
  sha256: 54b95d934cddd25b537dc34cf5c00476fb2b77ebba3e4663573030ba28397318

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/xrootd/
    - {{ pin_subpackage('xrootd', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - openssl
    - python
    - readline
    - libxml2
    - libuuid  # [not osx]
    - libcurl
    - krb5
    - zlib
    - ncurses
  run:
    - openssl
    - python
    - readline
    - libxml2
    - krb5
    - zlib
    - ncurses

test:
  imports:
    - XRootD.client
    - pyxrootd

about:
  home: http://xrootd.org/
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: High performance, scalable fault tolerant access to data

  description: |
    The XROOTD project aims at giving high performance, scalable fault tolerant
    access to data repositories of many kinds. The typical usage is to give
    access to file-based ones. It is based on a scalable architecture, a
    communication protocol, and a set of plugins and tools based on those. The
    freedom to configure it and to make it scale (for size and performance)
    allows the deployment of data access clusters of virtually any size, which
    can include sophisticated features, like authentication/authorization,
    integrations with other systems, WAN data distribution, etc.
  dev_url: https://github.com/xrootd/xrootd

extra:
  recipe-maintainers:
    - chrisburr
